

level_map = [
'                                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ',
'       XXXX                                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'                                            ',
'                 XX                         ',
'                                            ',
'P                   XX                      ',
'XX                      XXXXX   XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ',
'XX          XX        XXXXXXX   XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX  X   XXXX    XX  XXXXXXX   XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXX   XXXXX  XXXXX XXXXXXX   XXXXX XXXX  ',
'XXXXXXX   XXXXX XXXX  XXXXXXX   XXXXX XXXX  ',]


TILE_SIZE = 16
screen_width = 800
screen_height = len(level_map)*TILE_SIZE